### ISSUE TITLE
[BUG] Prison forever! .. yes really!

### ISSUE THREAD

**Issue by xH0RIZ0Nx** [lastnexusdev/GTA-Athena#13]
**Describe the bug**
Get sent to Prison and you can never leave unless you get Teleported out. Death just makes you a Fugitive.

**To Reproduce**
Commit a crime and get sent to prison

**Screenshots / Videos**
Go see you lazy fuck

**Additional context**
Death also take all items and sends you back to the hospital

**Comment by MomoSuperSpeed** [comment]
Yes it is an issue if you are trying to get out of jail legit by waiting for your time to complete.  After you walk out of the door from the cafeteria (Which is technically supposed to be locked btw)  You are met with a fence door that is locked and can only be unlocked by police.  This door is the obstacle to reach the front building where the NPC is located to release you from prison. 
If possible perhaps move this NPC inside the prison grounds so going to this building is unnecessary?  Or maybe make it so while your in prison your job changes to prisoner and blacklist all prisoners from being able to open those doors.  When they are released from prison their job changes to unemployed and then they are able to open the doors?  Maybe thats one way?

Technically...theres a way to break out of prison (In the game's current state) without waiting, just requires a bit of parkour, fighting, and luck.  Though havent tested this with the new lock system.  However, you WILL NOT get back your stuff that they took from you when you do this.  Because of the game's current state even when waiting like a good inmate for my time to expire I will still have to end up breaking out of prison just to break the fence so I can get to the building where the guard NPC is to release me legally.

**Comment by jhina5422** [comment]
Additional ways to break out of the prisons have been reported. semi-related. Still investigating how to fix both the timing and the escape bugs.

**Comment by xH0RIZ0Nx** [comment]
https://www.gta5-mods.com/maps/prison-fences-in-front-of-the-stairs-in-the-prison-ymap-xml-menyoo possible fix for the Momos way of getting out. Is it possible using the current qbcore prison script to have it TP you after sentence is up to just outside the main gate
